//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CameraModel()
        {
            this.ModelWebsites = new HashSet<ModelWebsite>();
            this.CameraModelNotes = new HashSet<CameraModelNote>();
        }
    
        public int CameraModelID { get; set; }
        public string CameraModelName { get; set; }
        public int CameraModelGender { get; set; }
        public bool Deleted { get; set; }
        public Nullable<bool> AllNudes { get; set; }
        public Nullable<bool> AllBonjour { get; set; }
        public Nullable<bool> AllTFP { get; set; }
    
        public virtual GenderType GenderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelWebsite> ModelWebsites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CameraModelNote> CameraModelNotes { get; set; }
    }
}
