//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAction
    {
        public int EventActionsID { get; set; }
        public int GivingPersonID { get; set; }
        public int ReveivingPersonID { get; set; }
        public int ActionID { get; set; }
        public int OwnerID { get; set; }
        public int EventID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Action Action { get; set; }
        public virtual TheEvent TheEvent { get; set; }
        public virtual UsersPeople UsersPeople { get; set; }
        public virtual UsersPeople UsersPeople1 { get; set; }
    }
}
