//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAction
    {
        public int ActionEventID { get; set; }
        public int EventID { get; set; }
        public int EntryPersonID { get; set; }
        public int EventPersonID { get; set; }
        public int ActionID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual Action Action { get; set; }
        public virtual Event Event { get; set; }
        public virtual EventPeople EventPeople { get; set; }
    }
}
