//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        public int ItemListID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public bool GotItem { get; set; }
        public Nullable<int> NumberOfItems { get; set; }
        public Nullable<int> SizeTypeID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateGot { get; set; }
        public string Notes { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SizeType SizeType { get; set; }
        public virtual Store Store { get; set; }
    }
}
