//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ListID { get; set; }
        public int FoodItemID { get; set; }
        public int UserID { get; set; }
        public int StoreID { get; set; }
        public bool GotItem { get; set; }
        public bool ShowOnAllLists { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
