//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Reps { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> ResistanceLevel { get; set; }
        public System.DateTime WorkedOutDate { get; set; }
        public bool IsDeleted { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
