//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mile
    {
        public int MilesID { get; set; }
        public bool Deleted { get; set; }
        public int ModfiyID { get; set; }
        public int AutoID { get; set; }
        public System.DateTime GasDate { get; set; }
        public Nullable<decimal> TotalGallons { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> TotalMilesDriven { get; set; }
        public Nullable<System.TimeSpan> EngineRunTime { get; set; }
        public int StationID { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual CreateModifyLog CreateModifyLog { get; set; }
    }
}
