//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model()
        {
            this.ModelSocialSites = new HashSet<ModelSocialSite>();
            this.ModelImages = new HashSet<ModelImage>();
        }
    
        public int ModelID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> ModfiyID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> AllNudes { get; set; }
        public Nullable<bool> AllBoudoir { get; set; }
        public Nullable<bool> AllErotica { get; set; }
        public string Notes { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelSocialSite> ModelSocialSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelImage> ModelImages { get; set; }
    }
}
