//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelSocialSite
    {
        public int ModelSocialID { get; set; }
        public int SocialSiteID { get; set; }
        public int ModelID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> ModfiyID { get; set; }
        public string URL { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual SocialSite SocialSite { get; set; }
    }
}
