//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<System.DateTime> PriceDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
