//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schema
    {
        public int SchemaID { get; set; }
        public bool Deleted { get; set; }
        public int ModfiyID { get; set; }
        public string SchemaName { get; set; }
    
        public virtual UserSchema UserSchema { get; set; }
    }
}
