//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheEvent
    {
        public int EventID { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public Nullable<System.DateTimeOffset> DateofEventOffSet { get; set; }
        public bool IsDeleted { get; set; }
        public string EventName { get; set; }
    }
}
