//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersChore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersChore()
        {
            this.UsersDoneChores = new HashSet<UsersDoneChore>();
        }
    
        public int UserChoreID { get; set; }
        public int UserID { get; set; }
        public int ChoreID { get; set; }
        public bool IsDeleted { get; set; }
        public int ChoreTimeTypeID { get; set; }
        public System.DateTime StartDateChore { get; set; }
        public bool IsDone { get; set; }
        public Nullable<System.DateTime> EndDateChore { get; set; }
        public int ChoreDayTimeTypeID { get; set; }
        public decimal AllowanceAmount { get; set; }
    
        public virtual Chore Chore { get; set; }
        public virtual ChoreTimeType ChoreTimeType { get; set; }
        public virtual User1 User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersDoneChore> UsersDoneChores { get; set; }
        public virtual ChoreDayTimeType ChoreDayTimeType { get; set; }
    }
}
