//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDoneChore
    {
        public int UsersDoneChoresID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime DateDone { get; set; }
        public int UserChoreID { get; set; }
    
        public virtual UsersChore UsersChore { get; set; }
    }
}
