//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPeople
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersPeople()
        {
            this.EventActions = new HashSet<EventAction>();
            this.EventActions1 = new HashSet<EventAction>();
        }
    
        public int UsersPersonID { get; set; }
        public string PersonName { get; set; }
        public int PersonGenderID { get; set; }
        public int UserID { get; set; }
        public string Notes { get; set; }
    
        public virtual User UsersID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAction> EventActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAction> EventActions1 { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
