//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightTracker
    {
        public int WeightID { get; set; }
        public Nullable<decimal> WeightAmout { get; set; }
        public Nullable<System.DateTime> WeightData { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
