//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhoPicked
    {
        public int WhoPickedAppID { get; set; }
        public int PlacePickedID { get; set; }
        public int PersonPickedID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User Users1 { get; set; }
        public virtual PlacesToGo PlacesToGo { get; set; }
    }
}
